### ISSUE TITLE
拉取项目之后不能正常加载

### ISSUE THREAD

**Issue by ChengTu-Lazy** [ilyfairy/DstServerQuery#2]
- 缺少很多的项目文件
![image](https://github.com/user-attachments/assets/0af95f19-bef1-46bb-a49d-2e1e2e22e40a)

- 构建脚本参数错误
![image](https://github.com/user-attachments/assets/d0ca72dc-802f-41c2-82cc-9d0364c37e15)

- 构建失败
![image](https://github.com/user-attachments/assets/cbb00e1c-a3a6-4316-a6ab-a44df9d12ed7)

**Comment by ilyfairy** [comment]
构建脚本忘记改了, git克隆的时候要加上--recursive参数, 不然拉取不到子模块  
`git clone --recursive https://github.com/ilyfairy/DstServerQuery`

**Comment by ilyfairy** [comment]
我忘记给moonsharp添加子模块了, 项目在 https://github.com/ilyfairy/moonsharp  
等我给加上

**Comment by ilyfairy** [comment]
现在能够正常构建了

**Comment by ChengTu-Lazy** [comment]
还是不行
![image](https://github.com/user-attachments/assets/ae7dd6df-d5e6-4657-bea7-9e301bb24534)

**Comment by ilyfairy** [comment]
你重新克隆一下, 看看`DstServerQuery\DstDownloader\moonsharp`是否存在

**Comment by ChengTu-Lazy** [comment]
好了，可以正常调试运行了
